### PR TITLE
Expose AsyncEnumerable on NETSTANDARD20 with dependency

### PR DESCRIPTION
**Pull request by adamhathcock**
Adds package for NET Standard 2.0 that allows for AsyncEnumerable usage

### CODE REVIEW

**Comment by adamhathcock** [comment]
This library helps greatly with Channels usage.  Unfortunately, some of my use cases are for .NET Framework still.  I hope this is accepted to stop me having to do the extension methods on my own.

**Comment by electricessence** [comment]
Did I miss somewhere that .NET Standard 2.0 supports `IAsyncEnumerable`? 2.1 does, and so does this library.
If you need pseudo `IAsyncEnumerable` it does exist, but not in a form that the compiler outright understands.
You can Use `reader.ReadAllAsync(async e => { })` to do the same.

**Comment by electricessence** [comment]
I'll take a look at adding the `Microsoft.Bcl` dependency, but no promises.

**Review by electricessence — APPROVED** [review]

**Comment by electricessence** [comment]
Gonna make some more adjustments, but this is definitely a win.

**Comment by electricessence** [comment]
Here's the latest release:
https://www.nuget.org/packages/Open.ChannelExtensions/8.5.0

**Comment by electricessence** [comment]
Both v7 and v6 versions are also updated and released appropriately.

**Comment by adamhathcock** [comment]
thanks!

**Pull request merged**
