### PR TITLE
README - comment for Join example

### PR DESCRIPTION
**Pull request by tmenier**
I found "Join" to be a tad confusing for something that basically unbundles collections. Your other references to Linq equivalents are helpful, so I thought this might be helpful here. Thanks!

### CODE REVIEW

**Comment by electricessence** [comment]
I like where you're head is at here, but I'm worried that it could be confusing?
It's less an analog for `.SelectMany()` and more closely related to DataFlow batching and joining.
I'll reconsider adding more clarity around what .Join does.

**Comment by electricessence** [comment]
I made some more updates to the Readme in the master branch.
Thanks for the feedback. :)

**Comment by tmenier** [comment]
Great additions, added some much needed clarity!

**Comment by electricessence** [comment]
Thanks for caring and chiming in with your ideas. :)

**Pull request closed without merging**
